### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by kill4food** [sargue/mailgun#10]
Hi,
Each time i try to send an email it is delayed by few minutes until i receive it and i get the following error message (it doesn't crash, only appears):
W/Errors: The following warnings have been detected: WARNING: HK2 service reification failed for [org.glassfish.jersey.message.internal.DataSourceProvider] with an exception:
          MultiException stack 1 of 4
          java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: javax.activation.DataSource
              at org.glassfish.hk2.utilities.cache.LRUHybridCache.compute(LRUHybridCache.java:315)
              at org.glassfish.hk2.utilities.reflection.internal.ClassReflectionHelperImpl.getAllMethods(ClassReflectionHelperImpl.java:108)
              at org.jvnet.hk2.internal.Utilities.findInitializerMethods(Utilities.java:1341)
              at org.jvnet.hk2.internal.DefaultClassAnalyzer.getInitializerMethods(DefaultClassAnalyzer.java:107)
              at org.glassfish.jersey.internal.inject.JerseyClassAnalyzer.getInitializerMethods(JerseyClassAnalyzer.java:242)
              at org.jvnet.hk2.internal.Utilities.getInitMethods(Utilities.java:218)
              at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:145)
              at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:180)
              at org.jvnet.hk2.internal.SystemDescriptor.internalReify(SystemDescriptor.java:740)
              at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:694)
              at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:461)
              at org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2288)
              at org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:125)
              at org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1373)
              at org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1368)
              at org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:116)
              at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1430)
              at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1355)
              at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1344)
              at org.glassfish.jersey.internal.inject.Providers.getServiceHandles(Providers.java:354)
              at org.glassfish.jersey.internal.inject.Providers.getCustomProviders(Providers.java:201)
              at org.glassfish.jersey.message.internal.MessageBodyFactory.<init>(MessageBodyFactory.java:221)
              at java.lang.reflect.Constructor.newInstance(Native Method)
              at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1375)
              at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:272)
              at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:366)
              at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
              at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
              at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
              at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
              at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
              at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
              at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
              at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
              at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:774)
              at org.jvnet.hk2.internal.ServiceLocatorImpl.getUnqualifiedService(ServiceLocatorImpl.java:786)
              at org.jvnet.hk2.internal.IterableProviderImpl.get(IterableProviderImpl.java:111)
              at org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:97)
              at org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:67)
              at org.glassfish.jersey.process.internal.Stages$LinkedStage.apply(Stages.java:308)
              at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
          	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:25

**Comment by sargue** [comment]
Hello and thanks for using this library.

There are two parts in your issue.

1) The message delivery delay. This depends on a lot of factors and the Mailgun service itself. Check [this article](https://help.mailgun.com/hc/en-us/articles/203306890-I-just-submitted-a-lot-of-messages-Why-is-delivery-happening-so-slowly-) from Mailgun.

2) The warning. The error seems to be a related to not finding the class `javax.activation.DataSource` which is... a bit weird. Could you please show an example of code which triggers this error?

**Comment by kill4food** [comment]
Hi,

Thanks for the response.

I mentioned the delay to check if the warning has anything to do with it or
maybe it's because that it's sent from the default mailgun's domain (for
now).

Another reason for the problem might be how i compiled it.
i put the following lines:

compile ('net.sargue:mailgun:1.3.1') {
    exclude group: 'javax.inject', module: 'javax.inject'
}
compile 'org.glassfish.hk2.external:javax.inject:2.4.0-b34'

because i had had problems compiling it in the normal way, but i read in
some forum's thread that you have participated in it that some guy
succeeded to compile with this tweak.

this is how i send the email:

private static class SendEmail extends AsyncTask<String, Void, Void> {
   protected Void doInBackground(String... input) {
      Configuration configuration = new Configuration()
            .domain("sandbox2b969f24e05b4d169dd2724f1fd0e8bb.mailgun.org")
            .apiKey(MainActivity.emailToken)
            .from("Rivhit",
"Rivhit@sandbox2b969f24e05b4d169dd2724f1fd0e8bb.mailgun.org");

      if(MainActivity.copyEmail.isEmpty()) {
         Mail.using(configuration)
               .to(MainActivity.email)
               .subject("order number: " + input[0] + " for customer:
" + CustomerPick.chosenCustomer.getName())
               .text("new order\n" + input[1])
               .build()
               .send();
      }

       return null;

}

new SendEmail().execute(orderNum, orderLink);

**Comment by sargue** [comment]
I see.

After some google research it seems this problem is related to running Jersey 2 (the REST library used to send request to the mailgun service) over Android.

Please read this post series.

* https://blogs.oracle.com/japod/entry/jersey_2_x_client_on
* https://blogs.oracle.com/japod/entry/jersey_2_x_client_on1

I don't do Android development so I can't help you any further. I'm sorry.

**Comment by Ramkesh9** [comment]
Hi @kill4food @sargue ,  have you got any solution with this issue, actually same issue is also apearing to me .
if yes, please let me know.
Thank you

**Comment by sargue** [comment]
Sorry, I have no new information about this issue.
