### ISSUE TITLE
NoSuchMethodError 'void javax.ws.rs.core.MultivaluedMap.addAll(java.lang.Object, java.util.List)'

### ISSUE THREAD

**Issue by ryanjanborja** [sargue/mailgun#43]
Code snippet
```
log.info("Sending info to email...");
Configuration config = new Configuration()
      .domain(env.getProperty("mailgun.domain"))
      .apiKey(env.getProperty("mailgun.apiKey"))
      .from(request.getSender());

Mail
      .using(config)
      .to(request.getEmail())
      .subject(request.getSubject())
      .template(request.getTemplate())
      .build()
      .send();
```

Error
```
java.lang.NoSuchMethodError: 'void javax.ws.rs.core.MultivaluedMap.addAll(java.lang.Object, java.util.List)'
	at net.sargue.mailgun.MailForm.prepareSend(MailForm.java:42) ~[mailgun-1.10.0.jar:na]
	at net.sargue.mailgun.Mail.send(Mail.java:69) ~[mailgun-1.10.0.jar:na]
```

pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <artifactId>dost1services</artifactId>
    <groupId>ph.gov.dost.region1</groupId>
    <version>1.0-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <packaging>jar</packaging>
  <groupId>io.ryan</groupId>
  <artifactId>notification</artifactId>

  <dependencies>
    <dependency>
      <groupId>io.ryan</groupId>
      <artifactId>clients</artifactId>
      <version>1.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.ryan</groupId>
      <artifactId>amqp</artifactId>
      <version>1.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-sleuth</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-sleuth-zipkin</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-amqp</artifactId>
    </dependency>

    <dependency>
      <groupId>net.sargue</groupId>
      <artifactId>mailgun</artifactId>
      <version>1.10.0</version>
    </dependency>

    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <scope>runtime</scope>
    </dependency>

    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <version>2.1.210</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
```

**Comment by sargue** [comment]
I cannot reproduce it, your code snippet works on my side.

I suspect some problem with dependencies. Your build is probably pulling some newer versions of Jersey.

Could you please post your dependency list?

**Comment by ryeborja** [comment]
> 

I have updated my original post to include the dependencies. I'll continue to investigate on my end to determine if it's package issue or not. 

This is my old code prior to migrating with the dependency.
```java
JSONObject variables = new JSONObject();
variables.put("name", recipient);
variables.put("link", link);

MultivaluedMapImpl formData = new MultivaluedMapImpl();
formData.add("from", EMAIL_SENDER);
formData.add("to", recipient);
formData.add("subject", subject);
formData.add("template", template);
formData.add("h:X-Mailgun-Variables", variables);
```
How should I pass the key-value variables?

**Comment by sargue** [comment]
That `pom.xml` looks like part of a bigger project.

Could you post the resolved dependencies? Try running `mvn dependency:list` and posting the resulting list.

**Comment by sargue** [comment]
Closing due to inactivity.
