### ISSUE TITLE
java.lang.ClassNotFoundException: jakarta.ws.rs.client.ClientBuilder

### ISSUE THREAD

**Issue by hendisantika** [sargue/mailgun#44]
I have this error:
```
java.lang.ClassNotFoundException: jakarta.ws.rs.client.ClientBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]

```

I add these libs
```
 <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-client</artifactId>
            <version>2.25</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-multipart</artifactId>
            <version>3.0.6</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <version>6.1.0.Final</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.sargue</groupId>
            <artifactId>mailgun</artifactId>
            <version>1.10.0</version>
        </dependency>
```

Any suggestion?

Thanks

**Comment by hendisantika** [comment]
Still error.

Can You give me your full pom.xml?

**Comment by sargue** [comment]
I don't have any. Why don't **you** post your pom.xml ?

**Comment by hendisantika** [comment]
OK. IT works. Thanks
